name: Sync to GitLab

on:
  push:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to GitLab
        env:
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
          GITLAB_REPO: ${{ secrets.GITLAB_REPO }}
        run: |
          # Отключаем проверку SSL сертификата
          git config --global http.sslVerify false
          
          git remote add gitlab "https://oauth2:${GITLAB_TOKEN}@${GITLAB_REPO#https://}"
          git push --mirror gitlab